vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        post_images:
            uri_prefix: /images/dynamic/post
            upload_destination: '%kernel.project_dir%/public/images/dynamic/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true